workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 60
    scripts:
      - name: Run tests
        script: ./gradlew test
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - j.bilongo@ynote.africa


  android-workflow:
    name: Android Test
    max_build_duration: 120
    scripts:
      - name: Launch emulator
        script: |
          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
      - name: Test
        script: |
          set -e
          ./gradlew connectedAndroidTest
          adb logcat -d > emulator.log
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - j.bilongo@ynote.africa