workflows:
  simple-workflow:
    name: Native Android
    max_build_duration: 120
    scripts:
      - |
        # give permission test
        chmod +x gradlew
      - name: Run tests
        script: ./gradlew test
      - name: Build debug apk
        script: ./gradlew assembleDebug
    artifacts:
      - app/build/**/outputs/**/*.apk
    publishing:
      email:
        recipients:
          - j.bilongo@ynote.africa