query GetInsureeInquire($chfId: String) {
    insurees(
        chfId: $chfId
    ) {
        edges {
            node {
                chfId
                lastName
                otherNames
                dob
                gender {
                    gender
                }
                photos {
                    folder
                    filename
                    photo
                }
                family {
                    uuid
                    members {
                        edges {
                            node {
                                chfId
                                lastName
                                otherNames
                                dob
                                head
                                gender {
                                    gender
                                }
                                photos {
                                    folder
                                    filename
                                    photo
                                }
                                relationship {
                                    relation
                                }
                            }
                        }
                    }
                }
                insureePolicies {
                    edges {
                        node {
                            policy {
                                product {
                                    name
                                    code
                                    ceiling
                                    ceilingIp
                                    ceilingOp
                                    deductible
                                    deductibleIp
                                    deductibleOp
                                    maxNoAntenatal
                                    maxAmountAntenatal
                                    maxNoSurgery
                                    maxAmountSurgery
                                    maxNoConsultation
                                    maxAmountConsultation
                                    maxNoDelivery
                                    maxAmountDelivery
                                    maxNoHospitalization

                                    maxMembers
                                    maxNoVisits
                                    maxInstallments
                                    maxCeilingPolicy
                                    maxCeilingPolicyIp
                                    maxCeilingPolicyOp
                                    maxPolicyExtraMember
                                    maxPolicyExtraMemberIp
                                    maxPolicyExtraMemberOp
                                }
                                enrollDate
                                expiryDate
                                status
                                value
                            }
                        }
                    }
                }
            }
        }
    }
}
