name: CI

on:
  push:
    branches:
      branches: [ "test-csu" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: 'gradle'

      - name: Environment info
        run: |
          gradle --version

      - name: show gradlew permission
        run: |
          chmod +x gradlew

      # Run Tests Build
      - name: Run gradle tests
        run: ./gradlew testCsuDevDebugUnitTest --stacktrace

#      - name: build
#        run: |
#          ./gradlew assemblecsuDevDebug --stacktrace
#
#      - name: Environment info
#        run: |
#          gradle --version

#      - uses: actions/upload-artifact@v4
#        with:
#          name: claims-csu-${{github.run_number}}.apk
#          path: ./claimManagement/build/outputs/**/*.apk
#
#      - name: build
#        run: |
#          ./gradlew bundlecsuDevDebug --stacktrace
#
#      - name: Environment info
#        run: |
#          gradle --version
#
#      - uses: actions/upload-artifact@v4
#        with:
#          name: claims-csu-${{github.run_number}}.aab
#          path: ./claimManagement/build/outputs/**/*.aab

